import { definePreset } from '@primeuix/themes'
import Aura from '@primeuix/themes/aura'
import {
  type ButtonPassThroughMethodOptions,
  DialogService,
  Ripple,
  Tooltip,
} from 'primevue'
import AnimateOnScroll from 'primevue/animateonscroll'
import PrimeVue from 'primevue/config'
import ConfirmationService from 'primevue/confirmationservice'
import StyleClass from 'primevue/styleclass'
import ToastService from 'primevue/toastservice'

export enum FilterMatchMode {
  CONTAINS = 'contains',
  DATE_AFTER = 'dateAfter',
  DATE_BEFORE = 'dateBefore',
  DATE_IS = 'dateIs',
  EQUALS = 'equals',
  GREATER_THAN_OR_EQUAL_TO = 'gte',
  IN = 'in',
  LESS_THAN_OR_EQUAL_TO = 'lte',
  STARTS_WITH = 'startsWith',
}

export default defineNuxtPlugin((nuxtApp) => {
  nuxtApp.vueApp.use(PrimeVue, {
    filterMatchModeOptions: {
      date: [
        FilterMatchMode.DATE_IS,
        FilterMatchMode.DATE_BEFORE,
        FilterMatchMode.DATE_AFTER,
      ],
      enum: [FilterMatchMode.IN],
      equals: [FilterMatchMode.EQUALS],
      numeric: [
        FilterMatchMode.EQUALS,
        FilterMatchMode.GREATER_THAN_OR_EQUAL_TO,
        FilterMatchMode.LESS_THAN_OR_EQUAL_TO,
      ],
      text: [FilterMatchMode.CONTAINS, FilterMatchMode.STARTS_WITH],
    },
    locale: {
      accept: 'はい',
      addRule: '条件追加',
      am: '午前',
      apply: '適用',
      aria: {
        cancelEdit: 'キャンセル',
        close: '閉じる',
        collapseLabel: '崩壊',
        collapseRow: '折りたたみ行',
        editRow: '行編集',
        expandLabel: '拡大する',
        expandRow: '展開済行',
        falseLabel: 'False',
        filterConstraint: 'フィルター成約',
        filterOperator: 'フィルター操作',
        firstPageLabel: '最初のページ',
        gridView: 'グリッドビュー',
        hideFilterMenu: 'フィルターメニューを非表示',
        jumpToPageDropdownLabel: 'ページドロップダウンへ',
        jumpToPageInputLabel: 'ページ入力へ',
        lastPageLabel: '最後のページ',
        listLabel: 'オプションリスト',
        listView: 'リストビュー',
        moveAllToSource: 'ソースへ全て移動',
        moveAllToTarget: 'ターゲットへ全て移動',
        moveBottom: '一番下へ',
        moveDown: '下へ',
        moveTop: 'トップへ移動',
        moveToSource: 'ソースへ移動',
        moveToTarget: 'ターゲットへ移動',
        moveUp: '上へ',
        navigation: 'ナビゲーション',
        next: '次',
        nextPageLabel: '次のページ',
        nullLabel: '未選択',
        otpLabel: 'ワンタイム パスワードの文字 {0} を入力してください',
        pageLabel: '{page}ページ',
        passwordHide: 'パスワードを隠す',
        passwordShow: 'パスワードを表示',
        previous: '前',
        prevPageLabel: '前のページ',
        removeLabel: '取り除く',
        rotateLeft: '左に回転',
        rotateRight: '右に回転',
        rowsPerPageLabel: '行/ページ',
        saveEdit: '保存',
        scrollTop: 'トップへスクロール',
        selectAll: '全て選択',
        selectLabel: '選択する',
        selectRow: '選択済み行',
        showFilterMenu: 'フィルターメニューを表示',
        slide: 'スライド',
        slideNumber: '{slideNumber}',
        star: '1件のスター',
        stars: '{star}件のスター',
        trueLabel: 'True',
        unselectAll: 'すべての選択を解除',
        unselectLabel: '選択を解除します',
        unselectRow: '未選択行',
        zoomImage: '画像を拡大',
        zoomIn: '拡大',
        zoomOut: '縮小',
      },
      cancel: 'キャンセル',
      choose: '選択',
      chooseDate: '日を選択',
      chooseMonth: '月を選択',
      chooseYear: '年を選択',
      clear: 'クリア',
      completed: '完了済',
      contains: '次のキーワードを含む',
      custom: 'カスタム',
      dateAfter: '次の日時以降',
      dateBefore: '次の日時以前',
      dateFormat: 'yy/mm/dd',
      dateIs: '次の日時と等しい',
      dateIsNot: '次の日時と等しくない',
      dayNames: [
        '日曜日',
        '月曜日',
        '火曜日',
        '水曜日',
        '木曜日',
        '金曜日',
        '土曜日',
      ],
      dayNamesMin: [
        '日',
        '月',
        '火',
        '水',
        '木',
        '金',
        '土',
      ],
      dayNamesShort: [
        '日',
        '月',
        '火',
        '水',
        '木',
        '金',
        '土',
      ],
      emptyFilterMessage: 'オプションなし',
      emptyMessage: '項目なし',
      emptySearchMessage: '該当なし',
      emptySelectionMessage: '選択なし',
      endsWith: '次のキーワードと後方一致',
      equals: '次の値と等しい',
      fileChosenMessage: '{0} ファイル',
      fileSizeTypes: [
        'B',
        'KB',
        'MB',
        'GB',
        'TB',
        'PB',
        'EB',
        'ZB',
        'YB',
      ],
      filter: 'フィルター',
      firstDayOfWeek: 0,
      gt: '次の値を超える',
      gte: '次の値以上',
      lt: '次の値未満',
      lte: '次の値以下',
      matchAll: '全て一致',
      matchAny: 'いずれかが一致',
      medium: '普通',
      monthNames: [
        '1月',
        '2月',
        '3月',
        '4月',
        '5月',
        '6月',
        '7月',
        '8月',
        '9月',
        '10月',
        '11月',
        '12月',
      ],
      monthNamesShort: [
        '1月',
        '2月',
        '3月',
        '4月',
        '5月',
        '6月',
        '7月',
        '8月',
        '9月',
        '10月',
        '11月',
        '12月',
      ],
      nextDecade: '後の10年',
      nextHour: '次の時間',
      nextMinute: '次の分',
      nextMonth: '翌月',
      nextSecond: '次の秒',
      nextYear: '翌年',
      noFileChosenMessage: 'ファイルが選択されていません',
      noFilter: 'フィルターなし',
      notContains: '次のキーワードを含まない',
      notEquals: '次の値と等しくない',
      now: '今',
      passwordPrompt: 'パスワードを入力',
      pending: '保留',
      pm: '午後',
      prevDecade: '前の10年',
      prevHour: '前の時間',
      prevMinute: '前の分',
      prevMonth: '先月',
      prevSecond: '前の秒',
      prevYear: '前年',
      reject: 'いいえ',
      removeRule: '条件削除',
      searchMessage: '{0} 件の結果',
      selectionMessage: '{0} 件選択済み',
      showMonthAfterYear: true,
      startsWith: '次のキーワードと前方一致',
      strong: '強い',
      today: '今日',
      upload: 'アップロード',
      weak: '弱い',
      weekHeader: '週',
    },
    pt: {
      autocomplete: {
        inputChip: 'flex-1 min-w-20',
        inputMultiple: 'items-start content-start',
      },
      button: {
        root: (options: ButtonPassThroughMethodOptions<unknown>) => ({
          class: [
            {
              ['min-w-28']: options.props.label,
            },
          ],
        }),
      },
      datatable: {
        column: {
          filterButtonbar: 'flex items-center justify-between gap-2',
        },
      },
      divider: {
        root: 'm-0',
      },
      inputgroup: {
        root: 'w-auto inline-flex',
      },
      splitbutton: {
        pcDropdown: {
          root: 'w-auto px-1',
        },
      },
    },
    ptOptions: {
      mergeProps: true,
      mergeSections: true,
    },
    theme: {
      options: {
        cssLayer: {
          name: 'primevue',
          order: 'theme, base, primevue',
        },
        darkModeSelector: '.app-dark',
      },
      preset: definePreset(Aura, {}),
    },
  })

  nuxtApp.vueApp.directive('styleclass', StyleClass)
  nuxtApp.vueApp.directive('animateonscroll', AnimateOnScroll)
  nuxtApp.vueApp.directive('ripple', Ripple)
  nuxtApp.vueApp.directive('tooltip', Tooltip)
  nuxtApp.vueApp.use(ToastService)
  nuxtApp.vueApp.use(ConfirmationService)
  nuxtApp.vueApp.use(DialogService)
})
